# Bem-vindos

No livro **Fundamentals of Data Science in Healthcare: Applications Using R** de André Peralta Santos, descobrirá como o RStudio (POSIT®) pode revolucionar a sua forma de interação com dados, promovendo uma análise data-driven com níveis elevados de eficiência e tirando partidos de novas técnicas, incluindo machine learning. Este livro ensina as práticas mais avançadas em ciência de dados, com foco particular na área da saúde, através de exemplos concretos e aplicáveis. Será exposto ao trabalho colaborativo, à automação de relatórios para partilha em formatos HTML ou Word, à criação de dashboards interativos, e ao uso do GitHub e do ChatGPT para gestão de versões e integração com inteligência artificial.

Ser-lhe-á proporcionado um conjunto de exemplos práticos com código e exercícios destinados a analisar dados reais, colaborar em projetos de complexidade variável, automatizar a geração de relatórios recorrentes e enriquecer as suas análises com painéis interativos. O livro está estruturado em oito módulos essenciais:

1.  Fundamentos de R
2.  Introdução ao Quarto
3.  Manipulação e Exploração de Dados
4.  Visualização de Dados
5.  Modelos Estatísticos
6.  Dashboards
7.  Introdução ao Machine Learning
8.  Tópicos Avançados em Ciência de Dados
9.  Projecto capstone

## Agradecimentos

Expressamos os nossos sinceros agradecimentos a João Dionísio pela sua revisão crítica e enriquecimento do código, especialmente nos módulos 1, 2, 6 e 8. Um agradecimento especial também a Manuel Ribeiro pela contribuição valiosa nos materiais do módulo 7.

## Licença

O conteúdo deste livro é disponibilizado sob a licença [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/), não sendo permitido o seu uso para fins comerciais.
