---
title: "Modulo 5 | Exercícios"
author: "A. Peralta-Santos"
date: today
date-format: long
lang: pt 
format:
  html:
    preview: false
    smooth-scroll: true
    embed-resources: true
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 3
    code_download: true
    code-copy: true
execute:
  warning: false
  collapse: true
  message: false
  eval: true
  echo: true
title-block-style: default
theme: templata_ensp
editor: 
  markdown: 
    wrap: 72
project:
  output-dir: outputs/documents
---

# Exercício - Hipotermia Cirúrgica

## Contexto

A hipotermia cirúrgica (definida como temperatura central < 36°C) é conhecida por causar coagulopatia, alteração no metabolismo de drogas, recuperação prolongada e desconforto térmico. Menos compreendido é se as infecções do sítio cirúrgico (ISCs) também estão associadas à hipotermia intraoperatória.

Isso é importante, pois as infecções do sítio cirúrgico são uma grande fonte de morbidade, mortalidade, prolongamento da hospitalização e custos de saúde. O risco geral de ISC é de 1 a 3%, geralmente, mas é substancialmente maior, 10 a 15%, para pacientes submetidos à cirurgia colorretal.

Literatura publicada até a data sugere que a hipotermia moderada causa ISCs e várias outras complicações. No entanto, alguns desses estudos estão desatualizados (os procedimentos cirúrgicos descritos já não são realizados) e muitos não possuem dados suficientes de temperatura intraoperatória. Portanto, é desconhecido se a hipotermia leve ou temperaturas normotérmicas influenciam o risco de infecção. [^1]

[^1]: *Fonte: The Core Temperature dataset was contributed by Ms. Jordyn Homoki, Research and Teaching Assistant, and Dr. Amy Nowacki, Associate Professor, Cleveland Clinic. Please refer to this resource as: Homoki, J. and Nowacki AS, "Core Temperature Dataset", TSHS Resources Portal (2023). Available at https://www.causeweb.org/tshs/core-temperature/.*

## Objetivo

Avaliar a relação entre a média ponderada do tempo (TWATemp) da temperatura central e as infecções graves de feridas e sistêmicas que se desenvolvem dentro de 30 dias após a cirurgia colorretal, no geral e após levar em conta as informações de covariáveis.

## Instruções

### Dataset

Use o dataset Core_Temperature.xlsx, e consulte a documentação em Core_Temperature_Data_Dictionary2.pdf na pasta de datasets. O objetivo geral do exercício é avaliar o efeito da temperatura (TWATemp) no risco de ISCs (AnyInfection).

### Estatística Descritiva

Deve criar uma Tabela 1 comparando a distribuição das variáveis de confundimento (Age, FEMALE, BMI, CharlsonScore, SurgeryType, CHF) pelos pacientes que tiveram ISC (AnyInfection).

### Visualização

Deve criar uma visualização comparando a distribuição da temperatura (TWATemp) pelo risco de ISCs (AnyInfection).

### Modelos

#### Univariado

Crie um modelo de regressão logística para avaliar o efeito da temperatura no risco de ISCs (AnyInfection).

#### Múltiplo

Crie um modelo de regressão logística para avaliar o efeito da temperatura no risco de ISCs (AnyInfection) ajustado para Age, FEMALE, BMI, CharlsonScore, SurgeryType, CHF.

#### Performance

Compare os dois modelos em termos de performance.

### Tabelas de Regressão

Crie uma tabela com os OR, p-value e Confidence Intervals do modelo construído em 6. Exporte a tabela criada em 8 para Word.

## FIM