---
title: "Módulo 9  | Capstone"
author: "A. Peralta-Santos"
date: today
date-format: long
lang: pt 
format:
  html:
    preview: false
    smooth-scroll: true
    embed-resources: true
    toc: true
    toc-location: right
    number-sections: true
    number-depth: 3
    code_download: true
    code-copy: true
execute:
  warning: false
  collapse: true
  message: false
  eval: true
  echo: true
title-block-style: default
theme: templata_ensp
editor: 
  markdown: 
    wrap: 72
project:
  output-dir: outputs/documents
---

# PROJECTO FINAL CAPSTONE

## Objetivo:

O ponto alto deste curso é o projeto final (Capstone).

O Capstone é a tua oportunidade de colocar em prática as novas
competências adquiridas em R e desenvolver o sua própria análise.

Pedimos que trabalhes com dados do mundo real, com questões de data
science criadas por ti.

Esforça-te para criar algo de que te orgulhes.

Como a data science raramente é um esforço individual, tens a
oportunidade de colaborar dois ou três colegas neste projeto final.

Esperamos que todos os membros de qualquer grupo contribuam de forma
igual no design e implementação do projeto.

Além disso, espera-se que a dimensão do projeto de um grupo de duas ou
três pessoas seja, respetivamente, o dobro ou o triplo da de um projeto
individual.

Incentivamos a colaboração entre grupos para resolver problemas do
código, desde que respeites as regras de honestidade académica do curso.

## Grupos

Os alunos devem criar grupos de 2 pessoas, 1 grupo de 3 pessoas. O
trabalho deve ser colaborativo.

Cada grupo fará a avaliação de um projecto de outro grupo.

## Fonte de dados

Os alunos podem trabalhar com um conjunto de dados de seu interesse ou
utilizar o dataset educativo (Base de dados modificada de morbilidade
hospitalar so SNS).

Devem informar se optam por usar dataset próprio ou dataset educativo.
Se usarem o dataset educativo devem enviar a *Minuta_MH_Estudantes_vc
(1).doc* assinada.

## Visão Geral do Projeto

O projeto envolverá manipulação de dados, análise exploratória de dados,
visualização de dados, inferência estatística, machine learning
(opcional) e a criação de um dashboard (opcional).

### Etapas do Projeto

1.  **Criação do Projeto**
    -   Utilize R para criar um projeto com o nome "GRUPO_N_CAPSTONE".
    -   Organize o projeto em pastas seguindo as melhores práticas e
        suas preferências.
2.  **Desenvolvimento do Contexto e Objetivos (Módulo 2)**
    -   Explique qual base de dados utilizou e descreva as variáveis
        empregadas, assim como o objetivo da exploração da base de
        dados.
    -   O código de suas análises deve estar visível.
    -   Utilize pelo menos 3 funcionalidades do módulo 2 (referências,
        inline coding, adicionar imagem).
3.  **Análise Exploratória dos Dados (Módulo 3)**
    -   Desenvolva uma análise exploratória dos dados de pelo menos 3
        variáveis.
    -   Documento erros da base e o que fez para os resolver.
4.  **Visualização de Dados (Módulo 4)**
    -   Desenvolva visualizações de dados usando ggplot2, podendo
        incluir dados espaciais.
    -   Deve apresentar pelo menos 3 figuras diferentes.
5.  **Modelos Estatísticos (Módulo 5)**
    -   Desenvolva uma tabela sumária de dados.
    -   OPCIONAL: Elabore um modelo de regressão, apresentando os
        resultados em uma tabela e num gráfico.
    -   OPCIONAL: Pode desenvolver um modelo de machine learning como
        alternativa (Módulo 6).
6.  **Integração e Automação (Módulo 6)**
    -   OPCIONAL: Desenvolva um dashboard com os resultados obtidos.

## Entregáveis

1.  Um projeto R reproduzível.
2.  Um documento html ou dashboard (opcional) com uma breve apresentação
    resumindo a fonte de dados, metodologia e resultados do projeto.
3.  O projeto deve conter os elementos do ponto anterior.

## Datas Importantes

### Turma 1

-   21 Setembro - Envio dos grupos
-   28 Setembro - Envio da descrição do dataset
-   31 Outubro - Office hours de dúvidas
-   10 Novembro - Entrega do Capstone
-   15 Novembro - Entrega da nota do projecto revisto
-   16 Novembro - Apresentação e discussão do capstone

### Turma 2

-   28 Setembro - Envio dos grupos
-   25 Outubro - Envio da descrição do dataset
-   31 Outubro - Office hours de dúvidas
-   17 Novembro - Entrega do Capstone
-   22 Novembro - Entrega da nota do projecto revisto
-   23 Novembro - Apresentação e discussão do capstone

## Instruções de Envio

Todos os projetos finais devem ser submetidos através do Moodle em
ficheiro zip.

Submissões atrasadas não serão aceitas sem aprovação prévia.

A não submissão implica na não conclusão do curso.

## Avaliação Capstone

A avaliação do capstone é realizada pelos professores (50% da nota) e
pelos grupos de revisão (50% da nota). Os capstone são classificados de
0 a 20.

## Avaliação Geral

No final de cada módulo, são propostos 4 exercícios que visam avaliar a
assimilação dos conteúdos pelos alunos (cada exercicio é pontuado com
1,25 valores em caso de resolução e 0 valores em caso de não resolução).

A assiduidade é um elemento crucial na avaliação, exigindo-se a
participação em pelo menos dois terços das sessões online ou
presenciais.

A partipação em pelo menos 6 sessões é pontuada com 5 valores.

O projeto capstone representa 50% da nota final.

Nota final superior a 9.5 valores cumpre os critérios para aprovação.

RESUMO

Nota final = 0.25\* Nota de assiduidade + 0.25 \* Média da nota de
exercícios + 0.5 \* Nota no capstone.

# FIM
