---
title: "Module 5 | Exercise"
author: "aluno"
date: today
date-format: long
format:
  html:
    preview: false
    smooth-scroll: true
    embed-resources: true
    toc: true
    toc-location: left
    number-sections: true
    number-depth: 3
    code_download: true
    code-copy: true
execute:
  warning: false
  collapse: true
  message: false
  eval: true
  echo: true
title-block-style: default
editor: 
  markdown: 
    wrap: 72
project:
  output-dir: outputs/documents
---

#Dataset 

## Contexto
A hipotermia cirúrgica (definida como temperatura central < 36°C) é conhecida por causar coagulopatia , metabolismo de drogas alterado, recuperação prolongada e desconforto térmico. Menos compreendido é se a infeção da ferida cirurgiva(ISCs), também estão associadas à hipotermia intraoperatória. 

Isso é importante, poque as infeções do sítio cirúrgico são uma grande fonte de morbidade, mortalidade, prolongamento da hospitalização e custos de saúde. O risco geral de ISC é de 1–3%, geralmente, mas é substancialmente maior, 10-15%, para pacientes submetidos à cirurgia colorretal. 

Literatura publicada até à data sugerem que a hipotermia moderada causa ISCs e várias outras complicações. No entanto, alguns desses estudos estão desatualizados (os procedimentos cirúrgicos descritos já não são realizados) e muitos não possuem dados suficientes de temperatura intraoperatória. Portanto, é desconhecido se a hipotermia leve ou temperaturas normotérmicas influenciam o risco de infeção. 

## Objetivo
Avaliar a relação entre a média ponderada do tempo (TWATemp) da temperatura central e as infeções graves de feridas e sistêmicas que se desenvolvem dentro de 30 dias após a cirurgia colorretal, no geral e após levar em conta as informações de covariáveis.

*Fonte: The Core Temperature dataset was contributed by Ms. Jordyn Homoki, Research and Teaching Assistant, and Dr. Amy Nowacki, Associate Professor, Cleveland Clinic. Please refer to this resource as: Homoki, J. and Nowacki AS, “Core Temperature Dataset”, TSHS Resources Portal (2023). Available at https://www.causeweb.org/tshs/core-temperature/.*

## Instruções 

1. Usa o dataset Core_Temperature.xlsx, pode consultar a documentação em Core_Temperature_Data_Dictionary2. pdf na pasta de datasets. O objectivo geral do exercisio é avaliar o efeito da temperatura (TWATemp) no risco de ISCs (AnyInfection) 
3. Deve criar uma tabela 1 comparando a distribuição das variaveis de confundimento (Age	FEMALE	BMI	CharlsonScore	SurgeryType	CHF) pelos doentes que tiveram ISC (AnyInfection) 
4. Deve criar uma visualização comparando a distribuição da temperatura (TWATemp) pelo risco de ISCs (AnyInfection)
5. Crie um modelo de regressão logistica para avaliar o efeito da temperatura no risco de ISCs (AnyInfection) 
6. Crie um modelo de regressão logistica para avaliar o efeito da temperatura no risco de ISCs (AnyInfection) ajustado para  Age	FEMALE	BMI	CharlsonScore	SurgeryType	CHF
7. Compare os dois modelos em termos de performance 
8. Crie uma tabela com os OR, p value e Confidence Intervals do modelo construido em 6 
9. Exporte a tabela criada em 8 para word
