name: Send email using Quarto and blastula
on: 
  schedule:
    - cron: '0 9 1 * *'
jobs:
  render:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install dependencies
        run: |
          install.packages("blastula", type = "win.binary")
        shell: Rscript {0}
      - name: Update Report
        run: Rscript -e source("email_automatico.R")
      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add output/*
          git commit -am "commit on $(date)"
          git push origin main